// main provides a server to serve the docs
// this is the only file that should be edited
// in this repository, the rest is autogenerated
package main

import (
	"embed"
	log "log/slog"
	"net/http"
	"os"
	"text/template"

	"github.com/hostwithquantum/runway-api-docs/docs"

	"github.com/gorilla/mux"
)

var (
	listen  string
	version = "dev"
	base    = ""

	//go:embed templates
	templates embed.FS

	//go:embed static
	static embed.FS
)

// page data
type PageData struct {
	BaseURL string
}

func init() {
	// set port
	if os.Getenv("PORT") != "" {
		listen = ":" + os.Getenv("PORT")
		base = "/api-docs"
	} else {
		listen = ":8484"
	}

	log.SetDefault(log.New(log.NewTextHandler(os.Stdout, &log.HandlerOptions{
		Level: log.LevelDebug,
	})).With(log.String("app", "runway-api-docs"), log.String("version", version)))
}

func main() {
	tmpl, err := template.ParseFS(templates, "templates/*.gotmpl")
	if err != nil {
		log.Error("loading templates", log.Any("err", err))
	}

	r := mux.NewRouter()
	r.Use(func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			log.Info("request", "method", r.Method, "path", r.URL.Path)
			next.ServeHTTP(w, r)
		})
	})
	r.NotFoundHandler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		log.Warn("not found", "method", r.Method, "path", r.URL.Path)
		http.NotFound(w, r)
	})

	if base != "" {
		r.HandleFunc(base, func(w http.ResponseWriter, r *http.Request) {
			http.Redirect(w, r, base+"/", http.StatusMovedPermanently)
		})
	}

	s := r.PathPrefix(base).Subrouter()
	s.PathPrefix("/swagger").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/", http.StatusPermanentRedirect)
	})
	s.HandleFunc("/docs/swagger.json", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write(docs.SwaggerJSON)
	})
	s.PathPrefix("/static/").Handler(http.StripPrefix(base, http.FileServerFS(static)))
	s.HandleFunc("/favicon.ico", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "https://ui.runway.horse/favicon.ico", http.StatusPermanentRedirect)
	})
	s.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if err := tmpl.ExecuteTemplate(w, "page.gotmpl", PageData{BaseURL: base}); err != nil {
			http.Error(w, "could not load page", http.StatusInternalServerError)
			log.Error("failed to load page", log.Any("err", err))
			return
		}
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
	})

	log.Info("Running on " + listen)
	http.ListenAndServe(listen, r)
}
